Algoritmo "crescente"

Var

   x, y : inteiro

Inicio


   escreval("Digite dois numeros: ")
   leia(x)
   leia(y)
   
   enquanto x <> y faca
   
            se x < y entao
               escreval("Crescente")
            senao
               escreval("Decrescente")
            fimse
            
            escreval("Digite outros dois numeros: ")
            leia(x)
            leia(y)
   
   
   
   
   fimenquanto




Fimalgoritmo